export enum NetworkKeys {
    Aga = "aga",
  }

export enum ActionType {
  // WALLET
  SET_BALANCE = "SET_BALANCE",
  SET_ASSETS = "SET_ASSETS",
  SET_ACCOUNT_ADDRESS = "SET_ACCOUNT_ADDRESS",
  SET_ACCOUNT_NAME = "SET_ACCOUNT_NAME",
  // USER
  SET_NAME = "SET_NAME",
  // AUTH
  SET_USER_ID = "SET_USER_ID",
  SET_HAS_WALLET = "SET_HAS_WALLET",
  SET_ACCESS_TOKEN = "SET_ACCCESS_TOKEN",
  SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN",
  SET_FCM_TOKEN = "SET_FCM_TOKEN",
  SET_LOGGED_IN = "SET_LOGGED_IN",
  // SET_LOGGED_OUT = "SET_LOGGED_OUT",

}
